export const CLICKHOUSE_MODULE_OPTIONS = 'CLICKHOUSE_MODULE_OPTIONS';
export const CLICKHOUSE_CONNECTION_NAME = 'CLICKHOUSE_CONNECTION_NAME';
export const DEFAULT_CONNECTION_NAME = 'DefaultClickHouseConnection';
